data: datasets/babel/train120.h5
sample: [
  work_dir/actformer/babel/epoch400.gen_100_per_class.h5,
  work_dir/actformer/babel/epoch500.gen_100_per_class.h5
]
work_dir: work_dir/eval_motion/babel_actformer
num_class: 120

# feeder
feeder: feeder.feeder_eval.Feeder
test_feeder_args:
  C: 6
  V: 25
  T: 64
  dataset: ntu

# model
weights: work_dir/recognition/babel/epoch80_model.pt
model: net.st_gcn.st_gcn.Model
model_args:
  in_channels: 6
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'smpl'
    strategy: 'spatial'

test_batch_size: 64
print_log: False