data: datasets/ntu120/data1p/xsub.train.h5
sample: [
  work_dir/actformer/ntu120_1p/epoch400.gen_100_per_class.h5,
  work_dir/actformer/ntu120_1p/epoch500.gen_100_per_class.h5,
]
work_dir: work_dir/eval_motion/ntu120_1p
num_class: 94

# feeder
feeder: feeder.feeder_eval.Feeder
test_feeder_args:
  C: 3
  V: 25
  T: 64
  dataset: ntu

# model
weights: work_dir/recognition/ntu120_1p/epoch80_model.pt
model: net.st_gcn.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 94
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

test_batch_size: 64
print_log: False
