data: datasets/ntu120/data2p/xsub.train.h5
sample: [
  work_dir/actformer/ntu120_2p/epoch500.gen_100_per_class.h5
]
work_dir: work_dir/eval_motion/ntu120_2p
num_class: 26

# feeder
feeder: feeder.feeder_eval.Feeder
test_feeder_args:
  C: 6
  V: 25
  T: 64
  dataset: ntu

# model
weights: work_dir/recognition/ntu120_2p/epoch80_model.pt
model: net.st_gcn.st_gcn.Model
model_args:
  in_channels: 6
  num_class: 26
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

test_batch_size: 64
print_log: False
