work_dir: work_dir/recognition/babel/

# feeder
feeder: feeder.feeder_resample.Feeder
resample: True
train_feeder_args:
  path: datasets/babel/val120.h5
  C: 6
  V: 25
  T: 64
  num_class: 120
  resample_p: 0.5
  random_crop: True
  dataset: ntu
test_feeder_args:
  path: datasets/babel/train120.h5
  C: 6
  V: 25
  T: 64
  num_class: 120
  resample_p: 1
  random_crop: True
  dataset: ntu
  
# model
model: net.st_gcn.st_gcn.Model
model_args:
  in_channels: 6
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'smpl'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: 0
batch_size: 64
test_batch_size: 64
num_epoch: 80



