work_dir: work_dir/recognition/ntu120_1p/

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  path: datasets/ntu120/data1p/xsub.test.h5
  C: 3
  V: 25
  T: 64
  random_crop: True
  dataset: ntu
test_feeder_args:
  path: datasets/ntu120/data1p/xsub.train.h5
  C: 3
  V: 25
  T: 64
  random_crop: True
  dataset: ntu
  
# model
model: net.st_gcn.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 94
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: 0
batch_size: 64 
test_batch_size: 64
num_epoch: 80



